name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  test:
    strategy:
      matrix:
        php-version: [ 8.1 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php-version }}"
          php_extensions: gmp

      - name: Run phpunit tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          php_version: "${{ matrix.php-version }}"
          php_extensions: gmp
          configuration: phpunit.xml

  create-release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
    outputs:
      releaseUrl: ${{ steps.release.outputs.url }}

  update-changelog:
    runs-on: ubuntu-latest
    needs:
      - create-release
    steps:
      - uses: actions/checkout@v3

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md